import type { CalendarEvent } from "@/lib/calendar/calendar-types";
import type { Contact } from "@/lib/contacts/contact-types";
import type { Note, NoteComment } from "@/lib/resources/resource-types";
import { defaultStatuses } from "./default-statuses";
import type { WorkspaceData } from "./workspace-types";

/**
 * Fixtures for the zero-configuration demo build. Dates are relative to the
 * moment the module loads so the dashboard widgets — upcoming deadlines in
 * particular — always have live-looking content instead of drifting into the
 * past the way pinned dates would.
 */
const dayMs = 24 * 60 * 60 * 1000;
const loadedAt = Date.now();

const at = (offsetDays: number, hour = 9, minute = 0) => {
  const moment = new Date(loadedAt + offsetDays * dayMs);
  moment.setHours(hour, minute, 0, 0);
  return moment.toISOString();
};

const on = (offsetDays: number) => at(offsetDays).slice(0, 10);

export const demoData: WorkspaceData = {
  canManageCategories: true,
  currentProfile: {
    id: "taylor",
    full_name: "Taylor Brooks",
    avatar_url: null,
    onboarding_completed: true,
    task_details_open_by_default: false,
    assign_new_tasks_to_self: false,
    editor_surface: "auto",
    calendar_default_view: ["task", "away", "important", "google"],
    favorite_project_ids: ["website-refresh"],
  },
  profiles: [
    {
      id: "taylor",
      full_name: "Taylor Brooks",
      avatar_url: null,
      onboarding_completed: true,
      task_details_open_by_default: false,
      assign_new_tasks_to_self: false,
      editor_surface: "auto",
      calendar_default_view: ["task", "away", "important", "google"],
      favorite_project_ids: ["website-refresh"],
    },
    {
      id: "alex",
      full_name: "Alex Morgan",
      avatar_url: null,
      onboarding_completed: true,
      task_details_open_by_default: false,
      assign_new_tasks_to_self: false,
      editor_surface: "auto",
      calendar_default_view: ["task", "away", "important", "google"],
      favorite_project_ids: [],
    },
    {
      id: "jordan",
      full_name: "Jordan Lee",
      avatar_url: null,
      onboarding_completed: true,
      task_details_open_by_default: false,
      assign_new_tasks_to_self: false,
      editor_surface: "auto",
      calendar_default_view: ["task", "away", "important", "google"],
      favorite_project_ids: [],
    },
  ],
  statuses: defaultStatuses.map((status, index) => ({
    ...status,
    id: ["backlog", "todo", "progress", "review", "done", "will-not-do"][index],
    order_revision: 0,
  })),
  categories: [
    {
      id: "operations",
      name: "Operations",
      description: "Day-to-day planning and internal team operations.",
      color: "#0f766e",
      links: [],
      tags: ["Chicago", "New York", "Los Angeles"],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "partnerships",
      name: "Partnerships",
      description: "Partner outreach, proposals, and shared commitments.",
      color: "#c2410c",
      links: [],
      tags: [],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "web",
      name: "Product / Tools",
      description: null,
      color: "#4338ca",
      links: [],
      tags: ["Feature", "Improvement", "Bug"],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "events",
      name: "Events",
      description: "Event logistics, schedules, and production.",
      color: "#be123c",
      links: [],
      tags: [],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "creative",
      name: "Creative",
      description: null,
      color: "#7c3aed",
      links: [],
      tags: [],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
    {
      id: "marketing",
      name: "Marketing",
      description: null,
      color: "#0891b2",
      links: [],
      tags: [],
      created_by: "taylor",
      archived_at: null,
      access_mode: "open",
    },
  ],
  projects: [
    {
      id: "website-refresh",
      name: "Website Refresh",
      description: "Content, design, and launch work for the new website.",
      links: [{ label: "Project brief", url: "https://example.com/brief" }],
      created_by: "taylor",
      archived_at: null,
      created_at: at(-45),
      start_date: on(-52),
      due_date: on(38),
      status: "active",
      access_mode: "open",
    },
    {
      id: "fall-launch",
      name: "Fall Launch",
      description: "Everything needed to prepare the fall product launch.",
      links: [],
      created_by: "taylor",
      archived_at: null,
      created_at: at(-30),
      start_date: null,
      due_date: null,
      status: "discovery",
      access_mode: "open",
    },
  ],
  subtasks: [],
  comments: [],
  activity: [
    {
      id: "activity-1",
      task_id: "11",
      actor_id: "taylor",
      action: "moved task",
      details: { from_status_id: "todo", status_id: "progress" },
      created_at: at(-0.2, 15, 40),
    },
    {
      id: "activity-2",
      task_id: "6",
      actor_id: "jordan",
      action: "moved task",
      details: { from_status_id: "todo", status_id: "progress" },
      created_at: at(-1, 11, 5),
    },
    {
      id: "activity-3",
      task_id: "8",
      actor_id: "alex",
      action: "moved task",
      details: { from_status_id: "progress", status_id: "review" },
      created_at: at(-1, 9, 20),
    },
    {
      id: "activity-4",
      task_id: "9",
      actor_id: "taylor",
      action: "moved task",
      details: { from_status_id: "backlog", status_id: "progress" },
      created_at: at(-2, 16, 15),
    },
    {
      id: "activity-5",
      task_id: "7",
      actor_id: "taylor",
      action: "moved task",
      details: { from_status_id: "backlog", status_id: "todo" },
      created_at: at(-3, 10, 30),
    },
    {
      id: "activity-6",
      task_id: "10",
      actor_id: "jordan",
      action: "moved task",
      details: { from_status_id: "backlog", status_id: "todo" },
      created_at: at(-4, 14, 0),
    },
    {
      id: "activity-7",
      task_id: "2",
      actor_id: "jordan",
      action: "moved task",
      details: { from_status_id: "progress", status_id: "review" },
      created_at: at(-5, 13, 45),
    },
    {
      id: "activity-8",
      task_id: "5",
      actor_id: "alex",
      action: "moved task",
      details: { from_status_id: "review", status_id: "done" },
      created_at: at(-6, 17, 10),
    },
    {
      id: "activity-9",
      task_id: "1",
      actor_id: "alex",
      action: "updated the task",
      details: {
        changes: [{ field: "priority", from: "high", to: "urgent" }],
      },
      created_at: at(-2, 12, 0),
    },
    {
      id: "activity-10",
      task_id: null,
      actor_id: "taylor",
      action: "note.create",
      details: {
        resource_type: "note",
        resource_id: "note-launch-retro",
        resource_name: "Launch retro takeaways",
      },
      created_at: at(-3, 8, 45),
    },
    {
      id: "activity-11",
      task_id: null,
      actor_id: "alex",
      action: "project.update",
      details: {
        resource_type: "project",
        resource_id: "fall-launch",
        resource_name: "Fall Launch",
        project_id: "fall-launch",
      },
      created_at: at(-7, 15, 25),
    },
  ],
  attachments: [],
  labels: [
    { id: "blocked", name: "Blocked", color: "#dc2626", created_by: "taylor" },
    { id: "website", name: "Website", color: "#4f46e5", created_by: "taylor" },
  ],
  taskAssignees: [
    { task_id: "1", profile_id: "alex" },
    { task_id: "1", profile_id: "taylor" },
    { task_id: "2", profile_id: "jordan" },
    { task_id: "2", profile_id: "alex" },
    { task_id: "4", profile_id: "taylor" },
    { task_id: "5", profile_id: "alex" },
    { task_id: "6", profile_id: "taylor" },
    { task_id: "7", profile_id: "taylor" },
    { task_id: "8", profile_id: "taylor" },
    { task_id: "9", profile_id: "taylor" },
    { task_id: "10", profile_id: "taylor" },
    { task_id: "11", profile_id: "taylor" },
    { task_id: "12", profile_id: "jordan" },
    { task_id: "13", profile_id: "alex" },
    { task_id: "14", profile_id: "taylor" },
  ],
  taskLabels: [],
  projectOwners: [
    { project_id: "website-refresh", profile_id: "taylor" },
    { project_id: "fall-launch", profile_id: "taylor" },
    { project_id: "fall-launch", profile_id: "alex" },
  ],
  categoryOwners: [
    { category_id: "events", profile_id: "taylor" },
    { category_id: "events", profile_id: "alex" },
    { category_id: "partnerships", profile_id: "taylor" },
    { category_id: "creative", profile_id: "alex" },
  ],
  taskCategories: [
    { task_id: "1", category_id: "events" },
    { task_id: "1", category_id: "marketing" },
    { task_id: "2", category_id: "partnerships" },
    { task_id: "2", category_id: "creative" },
    { task_id: "3", category_id: "operations" },
    { task_id: "4", category_id: "web" },
    { task_id: "5", category_id: "operations" },
    { task_id: "6", category_id: "web" },
    { task_id: "6", category_id: "creative" },
    { task_id: "7", category_id: "events" },
    { task_id: "8", category_id: "web" },
    { task_id: "9", category_id: "marketing" },
    { task_id: "10", category_id: "web" },
    { task_id: "11", category_id: "events" },
    { task_id: "11", category_id: "operations" },
    { task_id: "12", category_id: "marketing" },
    { task_id: "13", category_id: "creative" },
    { task_id: "14", category_id: "operations" },
  ],
  tasks: [
    {
      id: "1",
      task_number: 5,
      title: "Confirm launch venue",
      description: "Get the final room capacity and setup details.",
      status_id: "progress",
      project_id: "fall-launch",
      created_by: "taylor",
      reported_by: "jordan",
      start_date: on(-4),
      due_date: on(5),
      due_time: null,
      reminder_at: null,
      priority: "urgent",
      board_position: 1024,
      completed_at: null,
      archived_at: null,
      created_at: at(-8),
      updated_at: at(-2, 12, 0),
    },
    {
      id: "2",
      task_number: 4,
      title: "Refresh partner brief",
      description: "Update the proposal, benefits, and launch timeline.",
      status_id: "review",
      project_id: "website-refresh",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: on(7),
      due_time: null,
      reminder_at: null,
      priority: "high",
      board_position: 2048,
      completed_at: null,
      archived_at: null,
      created_at: at(-9),
      updated_at: at(-5, 13, 45),
    },
    {
      id: "3",
      task_number: 3,
      title: "Publish onboarding checklist",
      description: null,
      status_id: "todo",
      project_id: null,
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: on(3),
      due_time: null,
      reminder_at: null,
      priority: "medium",
      board_position: 3072,
      completed_at: null,
      archived_at: null,
      created_at: at(-10),
      updated_at: at(-10),
    },
    {
      id: "4",
      task_number: 2,
      title: "Fix confirmation email copy",
      description: "Keep it warm, short, and easy to understand.",
      status_id: "backlog",
      project_id: null,
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: on(11),
      due_time: null,
      reminder_at: null,
      priority: "low",
      category_tags: { web: ["Bug"] },
      board_position: 4096,
      completed_at: null,
      archived_at: null,
      created_at: at(-11),
      updated_at: at(-11),
    },
    {
      id: "5",
      task_number: 1,
      title: "Send customer interview thank-yous",
      description: null,
      status_id: "done",
      project_id: null,
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: on(-6),
      due_time: null,
      reminder_at: null,
      priority: "medium",
      board_position: 5120,
      completed_at: at(-6, 17, 10),
      archived_at: at(-1),
      created_at: at(-12),
      updated_at: at(-6, 17, 10),
    },
    {
      id: "6",
      task_number: 6,
      title: "Review homepage copy deck",
      description:
        "Read through the new hero and feature sections, then leave notes for the writer.",
      status_id: "progress",
      project_id: "website-refresh",
      created_by: "jordan",
      reported_by: "taylor",
      start_date: on(-1),
      due_date: on(2),
      due_time: "17:00",
      reminder_at: null,
      priority: "high",
      board_position: 6144,
      completed_at: null,
      archived_at: null,
      created_at: at(-6),
      updated_at: at(-1, 11, 5),
    },
    {
      id: "7",
      task_number: 7,
      title: "Lock in catering headcount",
      description: "The caterer needs a final number three days before setup.",
      status_id: "todo",
      project_id: "fall-launch",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: on(4),
      due_time: null,
      reminder_at: at(3, 9, 0),
      priority: "urgent",
      board_position: 7168,
      completed_at: null,
      archived_at: null,
      created_at: at(-7),
      updated_at: at(-3, 10, 30),
    },
    {
      id: "8",
      task_number: 8,
      title: "Ship the pricing page redesign",
      description: "Waiting on a final pass from design before it goes live.",
      status_id: "review",
      project_id: "website-refresh",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: on(-5),
      due_date: on(6),
      due_time: null,
      reminder_at: null,
      priority: "medium",
      board_position: 8192,
      completed_at: null,
      archived_at: null,
      created_at: at(-14),
      updated_at: at(-1, 9, 20),
    },
    {
      id: "9",
      task_number: 9,
      title: "Draft the launch announcement",
      description: "One short post plus a matching email to the mailing list.",
      status_id: "progress",
      project_id: "fall-launch",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: on(-2),
      due_date: on(9),
      due_time: null,
      reminder_at: null,
      priority: "high",
      board_position: 9216,
      completed_at: null,
      archived_at: null,
      created_at: at(-13),
      updated_at: at(-2, 16, 15),
    },
    {
      id: "10",
      task_number: 10,
      title: "Audit accessibility on checkout",
      description: "Keyboard traps, focus order, and contrast on every step.",
      status_id: "todo",
      project_id: "website-refresh",
      created_by: "alex",
      reported_by: "taylor",
      start_date: null,
      due_date: on(13),
      due_time: null,
      reminder_at: null,
      priority: "medium",
      board_position: 10240,
      completed_at: null,
      archived_at: null,
      created_at: at(-15),
      updated_at: at(-4, 14, 0),
    },
    {
      id: "11",
      task_number: 11,
      title: "Collect vendor insurance certificates",
      description: "Two vendors still owe paperwork before load-in day.",
      status_id: "progress",
      project_id: "fall-launch",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: on(-3),
      due_date: on(1),
      due_time: "12:00",
      reminder_at: at(0, 9, 0),
      priority: "urgent",
      board_position: 11264,
      completed_at: null,
      archived_at: null,
      created_at: at(-9),
      updated_at: at(-0.2, 15, 40),
    },
    {
      id: "12",
      task_number: 12,
      title: "Rewrite the welcome email sequence",
      description: "Three emails, sent across the first two weeks.",
      status_id: "review",
      project_id: null,
      created_by: "alex",
      reported_by: "alex",
      start_date: null,
      due_date: on(19),
      due_time: null,
      reminder_at: null,
      priority: "low",
      board_position: 12288,
      completed_at: null,
      archived_at: null,
      created_at: at(-16),
      updated_at: at(-6),
    },
    {
      id: "13",
      task_number: 13,
      title: "Archive last season's assets",
      description: null,
      status_id: "done",
      project_id: "website-refresh",
      created_by: "alex",
      reported_by: "alex",
      start_date: null,
      due_date: on(-9),
      due_time: null,
      reminder_at: null,
      priority: "low",
      board_position: 13312,
      completed_at: at(-9, 16, 0),
      archived_at: null,
      created_at: at(-20),
      updated_at: at(-9, 16, 0),
    },
    {
      id: "14",
      task_number: 14,
      title: "Set up analytics dashboards",
      description: "Traffic, signups, and drop-off for the new funnel.",
      status_id: "backlog",
      project_id: "website-refresh",
      created_by: "taylor",
      reported_by: "taylor",
      start_date: null,
      due_date: null,
      due_time: null,
      reminder_at: null,
      priority: "low",
      board_position: 14336,
      completed_at: null,
      archived_at: null,
      created_at: at(-18),
      updated_at: at(-18),
    },
    // Declined work, already archived: the fixture that shows the archive
    // holding both endings rather than only the finished ones.
    {
      id: "15",
      task_number: 15,
      title: "Print branded lanyards for every attendee",
      description: "Priced out at three vendors and cut from this event.",
      status_id: "will-not-do",
      project_id: "fall-launch",
      created_by: "taylor",
      reported_by: "jordan",
      start_date: null,
      due_date: on(-20),
      due_time: null,
      reminder_at: null,
      priority: "low",
      board_position: 15360,
      completed_at: at(-17, 11, 30),
      archived_at: at(-3),
      created_at: at(-24),
      updated_at: at(-17, 11, 30),
    },
  ],
};

export const demoNotes: Note[] = [
  {
    id: "note-launch-retro",
    title: "Launch retro takeaways",
    body: "Three things worth repeating next time:\n\n- The shared run-of-show doc kept everyone on the same page.\n- Booking the venue walkthrough early caught the power issue.\n- Sending the recap the same day got far more replies.\n\nOne thing to fix: we sat on vendor paperwork for a week.",
    category_id: "operations",
    created_by: "taylor",
    converted_task_id: null,
    converted_project_id: null,
    created_at: at(-3, 8, 45),
    updated_at: at(-3, 8, 45),
    archived_at: null,
  },
  {
    id: "note-homepage-ideas",
    title: "Homepage rewrite ideas",
    body: "Lead with what the product does in one sentence, then the proof.\n\nWorth stealing from the brief: https://example.com/brief\n\nKeep the feature grid to six items so it still reads on a phone.",
    category_id: "creative",
    created_by: "jordan",
    converted_task_id: "6",
    converted_project_id: null,
    created_at: at(-6, 10, 15),
    updated_at: at(-2, 9, 30),
    archived_at: null,
  },
  {
    id: "note-vendor-shortlist",
    title: "Vendor shortlist",
    body: "Lantern Room is the front-runner: right capacity, in-house AV, and they hold dates without a deposit.\n\nBackups are Harbor Hall (cheaper, no AV) and the community center (free, awkward layout).",
    category_id: "events",
    created_by: "taylor",
    converted_task_id: null,
    converted_project_id: null,
    created_at: at(-8, 14, 20),
    updated_at: at(-5, 11, 0),
    archived_at: null,
  },
  {
    id: "note-support-themes",
    title: "What people keep asking support",
    body: "Same four questions every week:\n\n1. How do I move a task to another project?\n2. Can I get a reminder the day before something is due?\n3. Why can't my teammate see this board?\n4. Where did my draft go?\n\nAll four are doc problems, not product problems.",
    category_id: "web",
    created_by: "alex",
    converted_task_id: null,
    converted_project_id: null,
    created_at: at(-11, 16, 5),
    updated_at: at(-11, 16, 5),
    archived_at: null,
  },
  {
    id: "note-old-pricing",
    title: "Old pricing experiment",
    body: "Kept for reference only. The two-tier test never shipped; see the pricing page work instead.",
    category_id: null,
    created_by: "taylor",
    converted_task_id: null,
    converted_project_id: null,
    created_at: at(-40, 13, 0),
    updated_at: at(-22, 13, 0),
    archived_at: at(-22, 13, 0),
  },
];

export const demoNoteComments: NoteComment[] = [
  {
    id: "note-comment-1",
    note_id: "note-launch-retro",
    body: "Agreed on the paperwork. I turned that into a task so it does not slip again.",
    created_by: "alex",
    created_at: at(-3, 9, 30),
    edited_at: null,
  },
  {
    id: "note-comment-2",
    note_id: "note-launch-retro",
    body: "Can we make the same-day recap part of the standard checklist?",
    created_by: "jordan",
    created_at: at(-2, 10, 10),
    edited_at: null,
  },
  {
    id: "note-comment-3",
    note_id: "note-homepage-ideas",
    body: "Six items works. I would cut the integrations row entirely.",
    created_by: "taylor",
    created_at: at(-2, 11, 45),
    edited_at: at(-2, 11, 50),
  },
  {
    id: "note-comment-4",
    note_id: "note-vendor-shortlist",
    body: "Lantern Room confirmed they can hold the date through the end of the month.",
    created_by: "alex",
    created_at: at(-5, 12, 15),
    edited_at: null,
  },
];

export const demoContacts: Contact[] = [
  {
    id: "contact-lantern-room",
    display_name: "The Lantern Room",
    image_url: null,
    image_path: null,
    contact_group: "Venue & Host",
    notes: "Capacity 180 seated. In-house AV and a loading dock off the alley.",
    created_at: at(-60),
    updated_at: at(-5, 12, 15),
    categories: [
      { id: "events", name: "Events", color: "#be123c" },
      { id: "operations", name: "Operations", color: "#0f766e" },
    ],
    people: [
      {
        id: "person-lantern-1",
        full_name: "Priya Raman",
        title: "Events Director",
        emails: [{ label: "Work", value: "events@example.com" }],
        phones: [{ label: "Office", value: "5551180142" }],
        instagram_handle: "lanternroom",
      },
      {
        id: "person-lantern-2",
        full_name: "Devon Clarke",
        title: "AV Lead",
        emails: [{ label: null, value: "av@example.com" }],
        phones: [],
        instagram_handle: null,
      },
    ],
  },
  {
    id: "contact-northside-coffee",
    display_name: "Northside Coffee Co.",
    image_url: null,
    image_path: null,
    contact_group: "Brand Partner",
    notes: "Sponsors the morning session. Needs artwork two weeks ahead.",
    created_at: at(-52),
    updated_at: at(-9),
    categories: [
      { id: "partnerships", name: "Partnerships", color: "#c2410c" },
      { id: "marketing", name: "Marketing", color: "#0891b2" },
    ],
    people: [
      {
        id: "person-northside-1",
        full_name: "Mara Ellis",
        title: "Partnerships Manager",
        emails: [
          { label: "Direct", value: "mara@example.com" },
          { label: "Team", value: "partners@example.com" },
        ],
        phones: [{ label: "Work cell", value: "5550194477" }],
        instagram_handle: "northsidecoffee",
      },
    ],
  },
  {
    id: "contact-good-fork",
    display_name: "Good Fork Catering",
    image_url: null,
    image_path: null,
    contact_group: "Event Vendor",
    notes: "Final headcount due three days out. Vegetarian options are strong.",
    created_at: at(-48),
    updated_at: at(-3, 10, 30),
    categories: [{ id: "events", name: "Events", color: "#be123c" }],
    people: [
      {
        id: "person-good-fork-1",
        full_name: "Ben Okafor",
        title: "Owner",
        emails: [{ label: null, value: "hello@example.com" }],
        phones: [{ label: null, value: "5550117723" }],
        instagram_handle: null,
      },
    ],
  },
  {
    id: "contact-daylight-press",
    display_name: "Daylight Press",
    image_url: null,
    image_path: null,
    contact_group: "Media & Press",
    notes: "Covered the spring launch. Prefers a two-week embargo window.",
    created_at: at(-41),
    updated_at: at(-14),
    categories: [{ id: "marketing", name: "Marketing", color: "#0891b2" }],
    people: [
      {
        id: "person-daylight-1",
        full_name: "Simone Ward",
        title: "Staff Writer",
        emails: [{ label: null, value: "tips@example.com" }],
        phones: [],
        instagram_handle: "daylightpress",
      },
    ],
  },
  {
    id: "contact-harbor-hall",
    display_name: "Harbor Hall",
    image_url: null,
    image_path: null,
    contact_group: "Venue & Host",
    notes: "Backup venue. Cheaper, but bring your own sound.",
    created_at: at(-38),
    updated_at: at(-20),
    categories: [{ id: "events", name: "Events", color: "#be123c" }],
    people: [
      {
        id: "person-harbor-1",
        full_name: "Rosa Iglesias",
        title: "Bookings",
        emails: [{ label: null, value: "book@example.com" }],
        phones: [{ label: null, value: "5550132298" }],
        instagram_handle: null,
      },
    ],
  },
  {
    id: "contact-pinewood-studio",
    display_name: "Pinewood Studio",
    image_url: null,
    image_path: null,
    contact_group: "Talent & Entertainment",
    notes: "Photo and video. Turnaround is about five business days.",
    created_at: at(-33),
    updated_at: at(-25),
    categories: [{ id: "creative", name: "Creative", color: "#7c3aed" }],
    people: [
      {
        id: "person-pinewood-1",
        full_name: "Casey Nolan",
        title: "Producer",
        emails: [{ label: null, value: "studio@example.com" }],
        phones: [],
        instagram_handle: "pinewoodstudio",
      },
    ],
  },
];

/** The calendar fixtures demo mode shows, shared by the calendar page and its editor routes. */
export const demoCalendarEvents: CalendarEvent[] = [
  {
    id: "demo-away",
    kind: "away",
    title: "Taylor is away",
    description: "Back online Monday.",
    starts_at: "2026-08-27T00:00:00",
    ends_at: "2026-08-30T23:59:00",
    all_day: true,
    recurrence: null,
    project_id: null,
    category_id: null,
    profile_id: "taylor",
    created_by: "taylor",
    created_at: "2026-08-20T12:00:00Z",
    updated_at: "2026-08-20T12:00:00Z",
  },
  {
    id: "demo-important",
    kind: "important",
    title: "Launch venue decision",
    description: "Final go/no-go date.",
    starts_at: "2026-08-24T00:00:00",
    ends_at: "2026-08-24T23:59:00",
    all_day: true,
    recurrence: null,
    project_id: "fall-launch",
    category_id: null,
    profile_id: null,
    created_by: "taylor",
    created_at: "2026-08-20T12:00:00Z",
    updated_at: "2026-08-20T12:00:00Z",
  },
  {
    id: "demo-recurring",
    kind: "important",
    title: "Weekly team sync",
    description: "Same time every week until launch.",
    starts_at: "2026-08-26T00:00:00",
    ends_at: "2026-08-26T23:59:00",
    all_day: true,
    recurrence: {
      frequency: "weekly",
      interval: 1,
      weekdays: [3],
      monthlyMode: "date",
      ends: { type: "never" },
    },
    project_id: null,
    category_id: null,
    profile_id: null,
    created_by: "taylor",
    created_at: "2026-08-20T12:00:00Z",
    updated_at: "2026-08-20T12:00:00Z",
  },
];
